- src: https://github.com/Oefenweb/ansible-locales.git
- src: yatesr.timezone
- src: geerlingguy.git
- src: ANXS.postgresql
- src: DavidWittman.redis
- src: https://github.com/pablocrivella/ansible-role-nvm.git
