---
- name: Server configuration
  hosts: all

  vars:
    rvm1_user: '{{ ansible_ssh_user }}'
    rvm1_ruby: '2.1.5'
    rvm1_gemset: 'angular-cycle-gallery'
    rvm1_rubies:
      - '{{ rvm1_ruby }}'
    rvm1_install_flags: '--auto-dotfiles --user-install'
    rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'

    nvm_env: user
    nvm_default_node_version: stable
    nvm_node_versions:
      - stable

    virtual_hosts:
      - { server_name: test-application.dev, root: /home/vagrant/test-application }
      - { server_name: gallery.dev, root: /home/vagrant/gallery/current/public }

  roles:
    - nginx
    - rvm_io.rvm1-ruby
    - nodesource.node

  tasks:
    - name: Add ssh user keys
      authorized_key: user=vagrant key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Add gemset
      command: "{{ rvm1_rvm }} {{ rvm1_ruby }} do rvm gemset create {{ rvm1_gemset }}"

    - name: Add bundler
      command: "{{ rvm1_rvm }} {{ rvm1_ruby }}@{{ rvm1_gemset }} do gem install bundler"

    - name: Add bower
      command: "npm install bower -g"
