---
- name: Server configuration
  hosts: all
  user: root

  vars:
    # Ruby settings
    rvm1_ruby: '2.3.0'
    rvm1_gemset: 'merchant'
    rvm1_rubies:
      - '{{ rvm1_ruby }}'
    rvm1_install_flags: '--auto-dotfiles --user-install'

    # Postgresql
    postgresql_databases:
      - name: merchant
        owner: merchant
    postgresql_users:
      - name: merchant
    postgresql_user_privileges:
      - name: merchant
        db: merchant
        priv: "ALL"

    # Project settings
    project_backend_path: '/home/merchant/backend'
    project_frontend_path: '/home/merchant/frontend'
    project_domain: 'http://merchant.lo:8081'
    project_user: 'merchant'

    # NodeJS
    nvm_env: system
    nvm_version: v0.31.0
    nvm_default_node_version: v5.10.1
    nvm_global_packages:
      - bower
      - gulp

    # Nginx settings
    virtual_hosts:
      - server_name: merchant.lo

  roles:
    - ansible-locales
    - yatesr.timezone
    - geerlingguy.git
    - ansible-role-nvm
    - ANXS.postgresql
    - DavidWittman.redis
    - rvm
    - rvm-gemsets
    - nginx
    - imagemagick
    - pg-dev
    - user-settings
    - hellapay-project
